/* auto-generated by scripts/importModes.ts; DO NOT EDIT MANUALLY */
import type { Mode } from '../models/Mode';

export const modes: Mode[] = [
  {
    "id": "on-jase",
    "name": "Dis-moi la vérité",
    "description": "Cathy te dit la vraie affaire: lucide, frontale, sans filtre inutile. Entre coach et claque dans face.",
    "emoji": "🎤",
    "kind": "delire"
  },
  {
    "id": "grill",
    "name": "Mets-moi sur le grill",
    "description": "Tu demandes le feu: roast, vérité dure et coaching sans coussin émotionnel.",
    "emoji": "🔥",
    "kind": "delire"
  },
  {
    "id": "radar-attitude",
    "name": "Radar d’Attitude",
    "description": "Mode désormais intégré à Dis-moi la vérité pour une conversation libre.",
    "emoji": "🔥",
    "kind": "chat"
  },
  {
    "id": "relax",
    "name": "Relax",
    "description": "Mode désormais intégré à Dis-moi la vérité pour une conversation libre.",
    "emoji": "😌",
    "kind": "delire"
  },
  {
    "id": "roast",
    "name": "Roast",
    "description": "Mode désormais intégré à Mets-moi sur le grill.",
    "kind": "chat"
  },
  {
    "id": "coach-brutal",
    "name": "Coach brutal",
    "description": "Mode désormais intégré à Mets-moi sur le grill.",
    "emoji": "💪",
    "kind": "delire"
  },
  {
    "id": "je-casse-tout",
    "name": "Je casse tout",
    "description": "Mode désormais intégré à Dis-moi la vérité pour une conversation libre.",
    "emoji": "💀",
    "kind": "delire"
  },
  {
    "id": "coach-de-vie",
    "name": "Coach de vie",
    "description": "Ton amie la plus franche: conseils concrets, vérité qui pique un peu, et zéro bullshit motivant.",
    "kind": "chat"
  },
  {
    "id": "message-personnalise",
    "name": "Message personnalisé",
    "description": "Donne le contexte (fête, rupture, félicitations), Cathy écrit le message que t'oses pas envoyer toi-même.",
    "kind": "chat"
  },
  {
    "id": "numero-de-show",
    "name": "Numéro de show",
    "description": "Un mini-numéro privé: intro, montée, punchline. Comme un extrait de scène direct dans ton cell.",
    "kind": "chat"
  },
  {
    "id": "horoscope",
    "name": "Horoscope",
    "description": "Les astres n'avaient rien demandé, mais Cathy lit ton destin avec panache et mauvaise foi assumée.",
    "kind": "chat"
  },
  {
    "id": "meteo",
    "name": "Meteo",
    "description": "La météo sans filtre: température, humeur du ciel et niveau de regret vestimentaire.",
    "kind": "chat"
  },
  {
    "id": "meme-generator",
    "name": "Générateur de Meme",
    "description": "Tu envoies une image, Cathy te sort le caption qui fait rire avant même le deuxième scroll.",
    "emoji": "😂",
    "kind": "image"
  },
  {
    "id": "screenshot-analyzer",
    "name": "Jugement de Texto",
    "description": "Capture ou texte collé: Cathy juge le sous-texte, ton style d’écriture et te donne la réplique à envoyer.",
    "emoji": "🔍",
    "kind": "image"
  },
  {
    "id": "roast-battle",
    "name": "Bataille de Roast",
    "description": "Tu lances un roast, Cathy répond et arbitre: léger, solide ou destruction totale.",
    "emoji": "⚔️",
    "kind": "battle"
  }
];

export const modesById: Record<string, Mode> = modes.reduce<Record<string, Mode>>((acc, mode) => {
  acc[mode.id] = mode;
  return acc;
}, {});

export function getModeById(modeId: string): Mode | null {
  return modesById[modeId] ?? null;
}
