/* auto-generated by scripts/importModes.ts; DO NOT EDIT MANUALLY */
import type { Mode } from '../models/Mode';

export const modes: Mode[] = [
  {
    "id": "radar-attitude",
    "name": "Radar d’Attitude",
    "description": "Le Radar d’Attitude active le mode approprié selon le comportement \"input\" de l'utilisateur",
    "emoji": "🔥"
  },
  {
    "id": "roast",
    "name": "Roast",
    "description": "Mode Roast."
  },
  {
    "id": "coach-de-vie",
    "name": "Coach de vie",
    "description": "Des conseils francs, un peu sarcastiques, mais toujours lucides. Pas de câlins gratuits, juste la vérité qui pique un peu."
  },
  {
    "id": "phrase-du-jour",
    "name": "Phrase du jour",
    "description": "Une citation originale, drôle ou absurde pour te partir la journée avec un petit coup de pied mental."
  },
  {
    "id": "message-personnalise",
    "name": "Message personnalisé",
    "description": "Bonne fête, retraite, rupture ou promotion. Cathy adapte son ton pour livrer le message que tu n’oses pas écrire."
  },
  {
    "id": "numero-de-show",
    "name": "Numéro de show",
    "description": "Un extrait inédit ou inspiré de scène. Comme si tu avais Cathy en mini-spectacle privé dans ton téléphone."
  },
  {
    "id": "horoscope",
    "name": "Horoscope",
    "description": "Des prédictions douteuses, mais étrangement précises. Les astres parlent… et ils ne sont pas toujours gentils."
  },
  {
    "id": "meteo",
    "name": "Meteo",
    "description": "Un bulletin météo revisité. Oui, il pleut. Non, tu ne vas pas prendre ton parapluie. Et oui, tu vas le regretter."
  }
];

export const modesById: Record<string, Mode> = modes.reduce<Record<string, Mode>>((acc, mode) => {
  acc[mode.id] = mode;
  return acc;
}, {});

export function getModeById(modeId: string): Mode | null {
  return modesById[modeId] ?? null;
}
