export const QUOTA_THRESHOLD_HAIKU_RATIO = 0.65;
export const QUOTA_THRESHOLD_SOFT_2_RATIO = 0.8;
export const QUOTA_THRESHOLD_SOFT_3_RATIO = 0.92;
export const QUOTA_THRESHOLD_HARD_FREE_RATIO = 1;
export const QUOTA_THRESHOLD_ABSOLUTE_PAID_RATIO = 1.5;
