export const QUOTA_THRESHOLD_SOFT_1_RATIO = 0.75;
export const QUOTA_THRESHOLD_SOFT_2_RATIO = 0.9;
export const QUOTA_THRESHOLD_HARD_FREE_RATIO = 1;
export const QUOTA_THRESHOLD_ABSOLUTE_PAID_RATIO = 1.5;
